In [ ]:
#Creamos un proyecto

!poetry new predictor-cliente

# AÃ±adimos las dependencias
!poetry add scikit-learn pandas ipykernel

## Preprocesamiento

In [55]:
# Importamos las librerias necesarias para este apartado

import pandas as pd

In [56]:
# Cargamos el csv y lo mostramos por pantalla

leads = pd.read_csv('Leads.csv')

leads

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.00,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.50,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.00,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.00,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9235,19d6451e-fcd6-407c-b83b-48e1af805ea9,579564,Landing Page Submission,Direct Traffic,Yes,No,1,8.0,1845,2.67,...,No,Potential Lead,Mumbai,02.Medium,01.High,15.0,17.0,No,No,Email Marked Spam
9236,82a7005b-7196-4d56-95ce-a79f937a158d,579546,Landing Page Submission,Direct Traffic,No,No,0,2.0,238,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,19.0,No,Yes,SMS Sent
9237,aac550fe-a586-452d-8d3c-f1b62c94e02c,579545,Landing Page Submission,Direct Traffic,Yes,No,0,2.0,199,2.00,...,No,Potential Lead,Mumbai,02.Medium,01.High,13.0,20.0,No,Yes,SMS Sent
9238,5330a7d1-2f2b-4df4-85d6-64ca2f6b95b9,579538,Landing Page Submission,Google,No,No,1,3.0,499,3.00,...,No,NaN,Other Metro Cities,02.Medium,02.Medium,15.0,16.0,No,No,SMS Sent
9239,571b5c8e-a5b2-4d57-8574-f2ffb06fdeff,579533,Landing Page Submission,Direct Traffic,No,No,1,6.0,1279,3.00,...,No,Potential Lead,Other Cities,02.Medium,01.High,15.0,18.0,No,Yes,Modified

In [57]:
# Listamos el tipo de columna

leads.dtypes

Prospect ID                                       object
Lead Number                                        int64
Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
How did you hear about X Education                object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                                          object
Newspaper Article                                 object
X Education Forums                                object
Newspaper                                         object
Digital Advertisement                             object
Through Recommendations                           object
Receive More Updates About Our Courses            object
Tags                                              object
Lead Quality                                      object
Update me on Supply Chain Content                 object
Get updates on DM Content                         object
Lead Profile                                      object
City                                              object
Asymmetrique Activity Index                       object
Asymmetrique Profile Index                        object
Asymmetrique Activity Score                      float64
Asymmetrique Profile Score                       float64
I agree to pay the amount through cheque          object
A free copy of Mastering The Interview            object
Last Notable Activity                             object
dtype: object

Vemos que cada columna tiene el tipo correcto, primero vamos a comprobar si tenemos valores duplicados en Lead Number y Prospect ID

In [58]:
# Comprobamos si tenemos valores duplicados en Lead Number y Prospect ID

print(sum(leads.duplicated(subset = 'Prospect ID')) == 0)
print(sum(leads.duplicated(subset = 'Lead Number')) == 0)

True
True

Vemos que ambas columnas tienen valores duplicados, por lo que lo eliminaremos ya que no tiene sentido tener clientes duplicados

In [59]:
# Eliminamos las columnas Lead Number y Prospect ID

leads = leads.drop(['Prospect ID', 'Lead Number'], axis = 1)

Vamos a comprobar el contenido de cada columna

In [60]:
# Mostramos por pantalla los contenidos de cada una de las columnas

for i in leads.columns:
    print(leads[i].value_counts(dropna = False))
    print('-----------------------------------')

Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: Lead Origin, dtype: int64
-----------------------------------
Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
NaN                    36
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: Lead Source, dtype: int64
-----------------------------------
No     8506
Yes     734
Name: Do Not Email, dtype: int64
-----------------------------------
No     9238
Yes       2
Name: Do Not Call, dtype: int64
-----------------------------------
0    5679
1    3561
Name: Converted, dtype: int64
-----------------------------------
0.0      2189
2.0      1680
3.0      1306
4.0      1120
5.0       783
6.0       466
1.0       395
7.0       309
8.0       224
9.0       164
NaN       137
10.0      114
11.0       86
13.0       48
12.0       45
14.0       36
16.0       21
15.0       18
17.0       16
18.0       15
20.0       12
19.0        9
21.0        6
23.0        6
24.0        5
25.0        5
27.0        5
22.0        3
29.0        2
28.0        2
26.0        2
141.0       1
55.0        1
30.0        1
43.0        1
74.0        1
41.0        1
54.0        1
115.0       1
251.0       1
32.0        1
42.0        1
Name: TotalVisits, dtype: int64
-----------------------------------
0       2193
60        19
74        18
75        18
127       18
        ...
1701       1
1952       1
1229       1
1743       1
927        1
Name: Total Time Spent on Website, Length: 1731, dtype: int64
-----------------------------------
0.00    2189
2.00    1795
3.00    1196
4.00     896
1.00     651
        ...
2.56       1
6.33       1
1.64       1
8.21       1
2.08       1
Name: Page Views Per Visit, Length: 115, dtype: int64
-----------------------------------
Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
NaN                              103
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: Last Activity, dtype: int64
-----------------------------------
India                   6492
NaN                     2461
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Bahrain                    7
Hong Kong                  7
Oman                       6
France                     6
unknown                    5
Kuwait                     4
South Africa               4
Canada                     4
Nigeria                    4
Germany                    4
Sweden                     3
Philippines                2
Uganda                     2
Italy                      2
Bangladesh                 2
Netherlands                2
Asia/Pacific Region        2
China                      2
Belgium                    2
Ghana                      2
Kenya                      1
Sri Lanka                  1
Tanzania                   1
Malaysia                   1
Liberia                    1
Switzerland                1
Denmark                    1
Russia                     1
Vietnam                    1
Indonesia                  1
Name: Country, dtype: int64
-----------------------------------
Select                               1942
NaN                                  1438
Finance Management                    976
Human Resource Management             848
Marketing Management                  838
Operations Management                 503
Business Administration               403
IT Projects Management                366
Supply Chain Management               349
Banking, Investment And Insurance     338
Travel and Tourism                    203
Media and Advertising                 203
International Business                178
Healthcare Management                 159
Hospitality Management                114
E-COMMERCE                            112
Retail Management                     100
Rural and Agribusiness                 73
E-Business                             57
Services Excellence                    40
Name: Specialization, dtype: int64
-----------------------------------
Select                   5043
NaN                      2207
Online Search             808
Word Of Mouth             348
Student of SomeSchool     310
Other                     186
Multiple Sources          152
Advertisements             70
Social Media               67
Email                      26
SMS                        23
Name: How did you hear about X Education, dtype: int64
-----------------------------------
Unemployed              5600
NaN                     2690
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: What is your current occupation, dtype: int64
-----------------------------------
Better Career Prospects      6528
NaN                          2709
Flexibility & Convenience       2
Other                           1
Name: What matters most to you in choosing a course, dtype: int64
-----------------------------------
No     9226
Yes      14
Name: Search, dtype: int64
-----------------------------------
No    9240
Name: Magazine, dtype: int64
-----------------------------------
No     9238
Yes       2
Name: Newspaper Article, dtype: int64
-----------------------------------
No     9239
Yes       1
Name: X Education Forums, dtype: int64
-----------------------------------
No     9239
Yes       1
Name: Newspaper, dtype: int64
-----------------------------------
No     9236
Yes       4
Name: Digital Advertisement, dtype: int64
-----------------------------------
No     9233
Yes       7
Name: Through Recommendations, dtype: int64
-----------------------------------
No    9240
Name: Receive More Updates About Our Courses, dtype: int64
-----------------------------------
NaN                                                  3353
Will revert after reading the email                  2072
Ringing                                              1203
Interested in other courses                           513
Already a student                                     465
Closed by Horizzon                                    358
switched off                                          240
Busy                                                  186
Lost to EINS                                          175
Not doing further education                           145
Interested  in full time MBA                          117
Graduation in progress                                111
invalid number                                         83
Diploma holder (Not Eligible)                          63
wrong number given                                     47
opp hangup                                             33
number not provided                                    27
in touch with EINS                                     12
Lost to Others                                          7
Still Thinking                                          6
Want to take admission but has financial problems       6
In confusion whether part time or DLP                   5
Interested in Next batch                                5
Lateral student                                         3
Shall take in the next coming month                     2
University not recognized                               2
Recognition issue (DEC approval)                        1
Name: Tags, dtype: int64
-----------------------------------
NaN                  4767
Might be             1560
Not Sure             1092
High in Relevance     637
Worst                 601
Low in Relevance      583
Name: Lead Quality, dtype: int64
-----------------------------------
No    9240
Name: Update me on Supply Chain Content, dtype: int64
-----------------------------------
No    9240
Name: Get updates on DM Content, dtype: int64
-----------------------------------
Select                         4146
NaN                            2709
Potential Lead                 1613
Other Leads                     487
Student of SomeSchool           241
Lateral Student                  24
Dual Specialization Student      20
Name: Lead Profile, dtype: int64
-----------------------------------
Mumbai                         3222
Select                         2249
NaN                            1420
Thane & Outskirts               752
Other Cities                    686
Other Cities of Maharashtra     457
Other Metro Cities              380
Tier II Cities                   74
Name: City, dtype: int64
-----------------------------------
NaN          4218
02.Medium    3839
01.High       821
03.Low        362
Name: Asymmetrique Activity Index, dtype: int64
-----------------------------------
NaN          4218
02.Medium    2788
01.High      2203
03.Low         31
Name: Asymmetrique Profile Index, dtype: int64
-----------------------------------
NaN     4218
14.0    1771
15.0    1293
13.0     775
16.0     467
17.0     349
12.0     196
11.0      95
10.0      57
9.0        9
18.0       5
8.0        4
7.0        1
Name: Asymmetrique Activity Score, dtype: int64
-----------------------------------
NaN     4218
15.0    1759
18.0    1071
16.0     599
17.0     579
20.0     308
19.0     245
14.0     226
13.0     204
12.0      22
11.0       9
Name: Asymmetrique Profile Score, dtype: int64
-----------------------------------
No    9240
Name: I agree to pay the amount through cheque, dtype: int64
-----------------------------------
No     6352
Yes    2888
Name: A free copy of Mastering The Interview, dtype: int64
-----------------------------------
Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: Last Notable Activity, dtype: int64
-----------------------------------

Vemos que tenemos muchas columnas que parecen que no son relevantes para nuestra prediccion, vamos a analizar sus contenidos..

In [61]:
# Revisamos las columnas Do Not Call, Do Not Email, Search, Magazine, Newspaper Article, Receive More Updates About Our Courses, X Education Forums, Newspaper, Digital Advertisement,
# Through Recommendations, Receive More Updates About Our Courses, Update me on Supply Chain Content, Get updates on DM Content, I agree to pay the amount through cheque y
# A free copy of Mastering The Interview para ver si son relevantes

print(leads['Do Not Call'].value_counts(dropna = False))
print(leads['Search'].value_counts(dropna = False))
print(leads['Magazine'].value_counts(dropna = False))
print(leads['Newspaper Article'].value_counts(dropna = False))
print(leads['Receive More Updates About Our Courses'].value_counts(dropna = False))
print(leads['X Education Forums'].value_counts(dropna = False))
print(leads['Newspaper'].value_counts(dropna = False))
print(leads['Digital Advertisement'].value_counts(dropna = False))
print(leads['Through Recommendations'].value_counts(dropna = False))
print(leads['Receive More Updates About Our Courses'].value_counts(dropna = False))
print(leads['Update me on Supply Chain Content'].value_counts(dropna = False))
print(leads['Get updates on DM Content'].value_counts(dropna = False))
print(leads['I agree to pay the amount through cheque'].value_counts(dropna = False))
print(leads['Do Not Email'].value_counts(dropna = False))
print(leads['A free copy of Mastering The Interview'].value_counts(dropna = False))

No     9238
Yes       2
Name: Do Not Call, dtype: int64
No     9226
Yes      14
Name: Search, dtype: int64
No    9240
Name: Magazine, dtype: int64
No     9238
Yes       2
Name: Newspaper Article, dtype: int64
No    9240
Name: Receive More Updates About Our Courses, dtype: int64
No     9239
Yes       1
Name: X Education Forums, dtype: int64
No     9239
Yes       1
Name: Newspaper, dtype: int64
No     9236
Yes       4
Name: Digital Advertisement, dtype: int64
No     9233
Yes       7
Name: Through Recommendations, dtype: int64
No    9240
Name: Receive More Updates About Our Courses, dtype: int64
No    9240
Name: Update me on Supply Chain Content, dtype: int64
No    9240
Name: Get updates on DM Content, dtype: int64
No    9240
Name: I agree to pay the amount through cheque, dtype: int64
No     8506
Yes     734
Name: Do Not Email, dtype: int64
No     6352
Yes    2888
Name: A free copy of Mastering The Interview, dtype: int64

Vemos que casi todo es "no", esto nos crearia ruido, provocando falsos negativos/positivos en nuestro modelo, por lo que los eliminaremos

In [62]:
# Eliminamos las columnas que podrian crear ruido

leads = leads.drop(['Do Not Call', 'Do Not Email', 'Search', 'Magazine', 'Newspaper Article', 'Receive More Updates About Our Courses', 'X Education Forums', 'Newspaper',
                     'Digital Advertisement', 'Through Recommendations', 'Receive More Updates About Our Courses', 'Update me on Supply Chain Content',
                     'Get updates on DM Content', 'I agree to pay the amount through cheque', 'A free copy of Mastering The Interview'], axis = 1)

Vamos a comprobar las columnas que tenemos..

In [63]:
# Comprobamos las columnas

leads.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9240 entries, 0 to 9239
Data columns (total 21 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Lead Origin                                    9240 non-null   object
 1   Lead Source                                    9204 non-null   object
 2   Converted                                      9240 non-null   int64
 3   TotalVisits                                    9103 non-null   float64
 4   Total Time Spent on Website                    9240 non-null   int64
 5   Page Views Per Visit                           9103 non-null   float64
 6   Last Activity                                  9137 non-null   object
 7   Country                                        6779 non-null   object
 8   Specialization                                 7802 non-null   object
 9   How did you hear about X Education             7033 non-null   object
 10  What is your current occupation                6550 non-null   object
 11  What matters most to you in choosing a course  6531 non-null   object
 12  Tags                                           5887 non-null   object
 13  Lead Quality                                   4473 non-null   object
 14  Lead Profile                                   6531 non-null   object
 15  City                                           7820 non-null   object
 16  Asymmetrique Activity Index                    5022 non-null   object
 17  Asymmetrique Profile Index                     5022 non-null   object
 18  Asymmetrique Activity Score                    5022 non-null   float64
 19  Asymmetrique Profile Score                     5022 non-null   float64
 20  Last Notable Activity                          9240 non-null   object
dtypes: float64(4), int64(2), object(15)
memory usage: 1.5+ MB

Vemos que hay muchas columnas que contienen la palabra "Select", eso significa que no contiene nada ya que el cliente no ha elegido ninguna opcion por lo que transformaremos "Select" en valores null

In [64]:
# comprobamos los valores null

import numpy as np
leads = leads.replace('Select', np.nan)

Vamos a comprobar las columas que contienen valores null

In [65]:
# Comprobamos las columas que contienen valores null

columnas_null = leads.isna().sum().to_frame(name='nÂº de null').sort_values('nÂº de null', ascending=False)
columnas_null

                                               nÂº de null
How did you hear about X Education                   7250
Lead Profile                                         6855
Lead Quality                                         4767
Asymmetrique Activity Index                          4218
Asymmetrique Profile Index                           4218
Asymmetrique Profile Score                           4218
Asymmetrique Activity Score                          4218
City                                                 3669
Specialization                                       3380
Tags                                                 3353
What matters most to you in choosing a course        2709
What is your current occupation                      2690
Country                                              2461
Page Views Per Visit                                  137
TotalVisits                                           137
Last Activity                                         103
Lead Source                                            36
Lead Origin                                             0
Total Time Spent on Website                             0
Converted                                               0
Last Notable Activity                                   0

Vemos que hay columnas que tienen mas de 3000 null, el tratarlas resultaria costoso ya que cada cliente es diferente por lo que procedemos a eliminarlas

In [66]:
# Eliminamos las columnas con mas de 3000 nulls

for i in leads.columns:
    if leads[i].isna().sum()>3000:
        leads.drop(i, axis=1, inplace=True)

Despues de la limpieza, vamos a tratar las columas que usaremos

In [67]:
# Comprobamos el contenido de las columnas

for i in leads.columns:
    print(leads[i].value_counts(dropna = False))
    print('-----------------------------------')

Landing Page Submission    4886
API                        3580
Lead Add Form               718
Lead Import                  55
Quick Add Form                1
Name: Lead Origin, dtype: int64
-----------------------------------
Google               2868
Direct Traffic       2543
Olark Chat           1755
Organic Search       1154
Reference             534
Welingak Website      142
Referral Sites        125
Facebook               55
NaN                    36
bing                    6
google                  5
Click2call              4
Press_Release           2
Social Media            2
Live Chat               2
youtubechannel          1
testone                 1
Pay per Click Ads       1
welearnblog_Home        1
WeLearn                 1
blog                    1
NC_EDM                  1
Name: Lead Source, dtype: int64
-----------------------------------
0    5679
1    3561
Name: Converted, dtype: int64
-----------------------------------
0.0      2189
2.0      1680
3.0      1306
4.0      1120
5.0       783
6.0       466
1.0       395
7.0       309
8.0       224
9.0       164
NaN       137
10.0      114
11.0       86
13.0       48
12.0       45
14.0       36
16.0       21
15.0       18
17.0       16
18.0       15
20.0       12
19.0        9
21.0        6
23.0        6
24.0        5
25.0        5
27.0        5
22.0        3
29.0        2
28.0        2
26.0        2
141.0       1
55.0        1
30.0        1
43.0        1
74.0        1
41.0        1
54.0        1
115.0       1
251.0       1
32.0        1
42.0        1
Name: TotalVisits, dtype: int64
-----------------------------------
0       2193
60        19
74        18
75        18
127       18
        ...
1701       1
1952       1
1229       1
1743       1
927        1
Name: Total Time Spent on Website, Length: 1731, dtype: int64
-----------------------------------
0.00    2189
2.00    1795
3.00    1196
4.00     896
1.00     651
        ...
2.56       1
6.33       1
1.64       1
8.21       1
2.08       1
Name: Page Views Per Visit, Length: 115, dtype: int64
-----------------------------------
Email Opened                    3437
SMS Sent                        2745
Olark Chat Conversation          973
Page Visited on Website          640
Converted to Lead                428
Email Bounced                    326
Email Link Clicked               267
Form Submitted on Website        116
NaN                              103
Unreachable                       93
Unsubscribed                      61
Had a Phone Conversation          30
Approached upfront                 9
View in browser link Clicked       6
Email Received                     2
Email Marked Spam                  2
Visited Booth in Tradeshow         1
Resubscribed to emails             1
Name: Last Activity, dtype: int64
-----------------------------------
India                   6492
NaN                     2461
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
United Kingdom            15
Australia                 13
Qatar                     10
Bahrain                    7
Hong Kong                  7
Oman                       6
France                     6
unknown                    5
Kuwait                     4
South Africa               4
Canada                     4
Nigeria                    4
Germany                    4
Sweden                     3
Philippines                2
Uganda                     2
Italy                      2
Bangladesh                 2
Netherlands                2
Asia/Pacific Region        2
China                      2
Belgium                    2
Ghana                      2
Kenya                      1
Sri Lanka                  1
Tanzania                   1
Malaysia                   1
Liberia                    1
Switzerland                1
Denmark                    1
Russia                     1
Vietnam                    1
Indonesia                  1
Name: Country, dtype: int64
-----------------------------------
Unemployed              5600
NaN                     2690
Working Professional     706
Student                  210
Other                     16
Housewife                 10
Businessman                8
Name: What is your current occupation, dtype: int64
-----------------------------------
Better Career Prospects      6528
NaN                          2709
Flexibility & Convenience       2
Other                           1
Name: What matters most to you in choosing a course, dtype: int64
-----------------------------------
Modified                        3407
Email Opened                    2827
SMS Sent                        2172
Page Visited on Website          318
Olark Chat Conversation          183
Email Link Clicked               173
Email Bounced                     60
Unsubscribed                      47
Unreachable                       32
Had a Phone Conversation          14
Email Marked Spam                  2
Approached upfront                 1
Resubscribed to emails             1
View in browser link Clicked       1
Form Submitted on Website          1
Email Received                     1
Name: Last Notable Activity, dtype: int64
-----------------------------------

In [68]:
# cambiamos los valores null por el valor mas indicado
 
leads['Lead Source'].fillna('Google', inplace=True)
leads['TotalVisits'].fillna(0.0, inplace=True)
leads['Country'].fillna('unknown', inplace=True)
leads['Page Views Per Visit'].fillna(0.0, inplace=True)
leads['Last Activity'].fillna('Not Specified', inplace=True)
leads['What is your current occupation'].fillna('Unemployed', inplace=True)
leads['What matters most to you in choosing a course'].fillna('Not Specified', inplace=True)

In [71]:
# Agrupamos datos similares y valores que aparecen pocas veces

leads['Lead Source'] = leads['Lead Source'].replace('google','Google')
leads['Lead Source'] = leads['Lead Source'].replace('Facebook','Social Media')
leads['Lead Source'] = leads['Lead Source'].replace(['bing','Click2call','Press_Release',
                                                     'youtubechannel','welearnblog_Home',
                                                     'WeLearn','blog','Pay per Click Ads',
                                                    'testone','NC_EDM','Live Chat'] ,'Others')

In [72]:
# Quitamos los espacios de todo el dataset

leads.columns = leads.columns.str.lower().str.replace(' ', '_')

string_columns = list(leads.dtypes[leads.dtypes == 'object'].index)
for col in string_columns:
    leads[col] = leads[col].str.lower().str.replace(' ', '_')

## Entrenamiento

In [73]:
# Importamos las librerias necesarias para este apartado

from sklearn.compose import make_column_selector as selector
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split

In [76]:
# Guardamos en una variable la columna objetivo

target = leads.converted

In [77]:
# eliminamos la columna objetivo
target = "converted"
target_colum = leads[target]

leads.drop(target, axis=1, inplace=True)

In [78]:
# Separamos las columnas por categoricas y numericas

categorical_columns_selector = selector(dtype_include=object)
categorical_columns = categorical_columns_selector(leads)
print(categorical_columns)

numerical_columns_selector = selector(dtype_exclude=object)
numerical_columns = numerical_columns_selector(leads)
print(numerical_columns)

['lead_origin', 'lead_source', 'last_activity', 'country', 'what_is_your_current_occupation', 'what_matters_most_to_you_in_choosing_a_course', 'last_notable_activity']
['totalvisits', 'total_time_spent_on_website', 'page_views_per_visit']

In [79]:
# Asignamos un preprocesador para cada tipo de columna

categorical_preprocessor = OneHotEncoder(handle_unknown="ignore")
numerical_preprocessor = StandardScaler()

In [80]:
# Creamos un pipeline preprocesador

preprocessor = ColumnTransformer([
    ('one-hot-encoder', categorical_preprocessor, categorical_columns),
    ('standard_scaler', numerical_preprocessor, numerical_columns)])

In [81]:
# Cremamos el modelo

model = make_pipeline(preprocessor, LogisticRegression(max_iter=500))

In [82]:
# Dividimos los datos

data_train, data_test, target_train, target_test = train_test_split(leads, target_colum)

In [83]:
# Entrenamos el modelo

model.fit(data_train, target_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('one-hot-encoder',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['lead_origin', 'lead_source',
                                                   'last_activity', 'country',
                                                   'what_is_your_current_occupation',
                                                   'what_matters_most_to_you_in_choosing_a_course',
                                                   'last_notable_activity']),
                                                 ('standard_scaler',
                                                  StandardScaler(),
                                                  ['totalvisits',
                                                   'total_time_spent_on_website',
                                                   'page_views_per_visit'])])),
                ('logisticregression', LogisticRegression(max_iter=500))])

In [84]:
# Mostramos por pantalla la efectividad del modelo

model.score(data_test, target_test)

0.8199134199134199

## Serializacion del modelo

In [85]:
# Importamos las librerias necesarias para este apartado

import pickle

In [86]:
# Serializamos el modelo

with open('models/potencial-client-model.pck', 'wb') as f:
    pickle.dump((model), f)

In [88]:
# Abrimos el modelo y probamos su funcionamiento

with open('models/potencial-client-model.pck', 'rb') as f:
    model = pickle.load(f)
    y_pred = model.predict(data_test[:1])

bool(y_pred[0])

False

## Creacion de la app con Flask

In [89]:
# AÃ±adimos Flask a nuestro pack

!poetry add flask

The following packages are already present in the pyproject.toml and will be skipped:

  â¢ flask

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.

In [91]:
# Levantamos la app

!poetry run python predictor_cliente/churn_predict_app.py

 * Serving Flask app 'predict' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 553-016-509
^C

## Pruebas

Para realizar el test correctamente verificaremos cual es el que realmente es potencial o no

In [ ]:
# Listamos las 10 primeras filas

target_test[:10]

4289    0
4953    0
1606    0
7275    0
3328    1
1736    0
1313    1
1556    0
6029    0
449     1
Name: converted, dtype: int64

Vemos que la primera y quinta fila da valores diferentes, es decir una de ellas el modelo nos tiene que decir que es cliente potencial y en la otra no

In [98]:
# Transformamos las columnas a json

data_test.iloc[0].to_json(r'ejemplo-true.json', orient = 'index')
data_test.iloc[4].to_json(r'ejemplo-false.json', orient = 'index')

In [99]:
# Prueba cliente NO potencial

!curl --request POST 'http://127.0.0.1:8000/predict' \
--header 'Content-Type: application/json' \
--data-raw '{"lead_origin":"landing_page_submission","lead_source":"direct_traffic","totalvisits":3.0,"total_time_spent_on_website":14,"page_views_per_visit":3.0,"last_activity":"sms_sent","country":"singapore","what_is_your_current_occupation":"unemployed","what_matters_most_to_you_in_choosing_a_course":"better_career_prospects","last_notable_activity":"sms_sent"}'

{
  "Converted": false
}

In [100]:
# Prueba cliente potencial

!curl --request POST 'http://127.0.0.1:8000/predict' \
--header 'Content-Type: application/json' \
--data-raw '{"lead_origin":"api","lead_source":"olark_chat","totalvisits":0.0,"total_time_spent_on_website":0,"page_views_per_visit":0.0,"last_activity":"sms_sent","country":"unknown","what_is_your_current_occupation":"unemployed","what_matters_most_to_you_in_choosing_a_course":"better_career_prospects","last_notable_activity":"sms_sent"}'

{
  "Converted": true
}